#!/usr/bin/env node
// Posts (or updates) one pull request comment summarising how the architecture changed, for the GitHub Action.
//
//   node pr-comment.mjs --base <older architecture.json> --head <newer architecture.json>
//
// Reads GITHUB_REPOSITORY, GITHUB_TOKEN and the pull request event (GITHUB_EVENT_PATH). It only ever talks to the GitHub API,
// never logs the token, and exits 0 when it cannot comment (for example on a fork, where the token is read-only), because a
// missing comment must never fail someone's build.
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { diffArchitectures } from './lib/core/diff-core.mjs';

export const MARKER = '<!-- gitvisualise-diff -->';
const SITE = 'https://kaushik2210.github.io/gitVisualise/';
const MAX_ITEMS = 8;

/** Text that is safe inside a Markdown table cell or list item: no HTML, no code fences, no pipes, one line. */
const plain = (s, max = 60) => {
  const t = String(s == null ? '' : s).replace(/[`<>|\\[\]]/g, '').replace(/\s+/g, ' ').trim();
  return t.length > max ? t.slice(0, max - 1) + '…' : t;
};

/**
 * @param diff  the result of diffArchitectures()
 * @returns Markdown, or null when nothing structural changed
 */
export function buildComment({ arch, summary }, { repo, baseSha, headSha, site = SITE } = {}) {
  if (summary.empty) return null;
  const n = summary.nodes, e = summary.edges;
  const list = (diff, kind) => {
    const items = arch[kind].filter((x) => x.diff === diff);
    if (!items.length) return null;
    const label = (x) => (kind === 'nodes' ? plain(x.label) : `${plain(arch.nodes.find((y) => y.id === x.from)?.label)} → ${plain(arch.nodes.find((y) => y.id === x.to)?.label)}${x.label ? ` (${plain(x.label, 30)})` : ''}`);
    const shown = items.slice(0, MAX_ITEMS).map((x) => `\`${label(x)}\``);
    return shown.join(', ') + (items.length > MAX_ITEMS ? `, and ${items.length - MAX_ITEMS} more` : '');
  };
  const row = (icon, name, count, names) => (count ? `| ${icon} ${name} | ${count} | ${names || ''} |` : null);
  const rows = [
    row('🟢', 'Components added', n.added, list('added', 'nodes')),
    row('🔴', 'Components removed', n.removed, list('removed', 'nodes')),
    row('🟠', 'Components changed', n.changed, list('changed', 'nodes')),
    row('🟢', 'Relationships added', e.added, list('added', 'edges')),
    row('🔴', 'Relationships removed', e.removed, list('removed', 'edges')),
    row('🟠', 'Relationships changed', e.changed, list('changed', 'edges')),
  ].filter(Boolean);
  const link = repo && baseSha && headSha ? `\n\n[See the changes as a tour →](${site}#/${repo}@${baseSha.slice(0, 12)}...${headSha.slice(0, 12)})` : '';
  return `${MARKER}\n### Architecture changes\n\n| | | |\n|---|---:|---|\n${rows.join('\n')}${link}\n\n<sub>Generated by [gitvisualise](https://github.com/Kaushik2210/gitVisualise) from the code in this pull request. Renamed or moved files show as one removal plus one addition.</sub>`;
}

export const NO_CHANGES_BODY = `${MARKER}\n### Architecture changes\n\nNo structural changes remain in this pull request.\n\n<sub>Generated by [gitvisualise](https://github.com/Kaushik2210/gitVisualise).</sub>`;

const api = (fetchImpl, token) => async (method, url, body) => {
  const res = await fetchImpl(`https://api.github.com${url}`, {
    method,
    headers: { accept: 'application/vnd.github+json', authorization: `Bearer ${token}`, 'x-github-api-version': '2022-11-28', ...(body ? { 'content-type': 'application/json' } : {}) },
    body: body ? JSON.stringify(body) : undefined,
  });
  return { status: res.status, data: res.status === 204 ? null : await res.json().catch(() => null) };
};

/**
 * Creates or updates the one comment this tool owns (found by MARKER). Never throws for API problems.
 *   body      the summary to post, or null when nothing changed
 *   whenClear what to write into an existing comment when body is null (so an old comment never reports stale news)
 * @returns { action: 'created' | 'updated' | 'none' | 'skipped', reason? }
 */
export async function postComment({ repo, prNumber, token, body, whenClear = NO_CHANGES_BODY, fetchImpl = globalThis.fetch }) {
  if (!repo || !prNumber || !token) return { action: 'skipped', reason: 'not running on a pull request with a token' };
  const call = api(fetchImpl, token);
  let existing = null;
  for (let page = 1; page <= 10 && !existing; page++) {
    const r = await call('GET', `/repos/${repo}/issues/${prNumber}/comments?per_page=100&page=${page}`);
    if (r.status !== 200 || !Array.isArray(r.data)) return { action: 'skipped', reason: `could not list comments (HTTP ${r.status})` };
    existing = r.data.find((c) => typeof c.body === 'string' && c.body.startsWith(MARKER)) || null;
    if (r.data.length < 100) break;
  }
  const text = body || (existing ? whenClear : null);
  if (!text) return { action: 'none' };
  const r = existing
    ? await call('PATCH', `/repos/${repo}/issues/comments/${existing.id}`, { body: text })
    : await call('POST', `/repos/${repo}/issues/${prNumber}/comments`, { body: text });
  if (r.status >= 200 && r.status < 300) return { action: existing ? 'updated' : 'created' };
  return { action: 'skipped', reason: `GitHub answered HTTP ${r.status}${r.status === 403 ? " (a fork's token is read-only)" : ''}` };
}

/** Diffs the two architectures and posts the result. */
export async function run({ baseFile, headFile, env = process.env, fetchImpl = globalThis.fetch }) {
  const read = (f) => JSON.parse(fs.readFileSync(f, 'utf8'));
  const base = read(baseFile), head = read(headFile);
  const event = env.GITHUB_EVENT_PATH && fs.existsSync(env.GITHUB_EVENT_PATH) ? JSON.parse(fs.readFileSync(env.GITHUB_EVENT_PATH, 'utf8')) : {};
  const pr = event.pull_request || {};
  const diff = diffArchitectures(base, head, { baseRef: 'base', headRef: 'this pull request' });
  const body = buildComment(diff, { repo: env.GITHUB_REPOSITORY, baseSha: (pr.base && pr.base.sha) || '', headSha: (pr.head && pr.head.sha) || '' });
  const posted = await postComment({ repo: env.GITHUB_REPOSITORY, prNumber: pr.number || event.number, token: env.GITHUB_TOKEN, body, fetchImpl });
  return { ...posted, summary: diff.summary };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2);
  const opt = (name) => { const i = args.indexOf(`--${name}`); return i >= 0 ? args[i + 1] : null; };
  const baseFile = opt('base'), headFile = opt('head');
  if (!baseFile || !headFile) { console.error('usage: pr-comment.mjs --base <architecture.json> --head <architecture.json>'); process.exit(2); }
  try {
    const r = await run({ baseFile, headFile });
    const s = r.summary;
    console.log(`Architecture diff: components +${s.nodes.added} -${s.nodes.removed} ~${s.nodes.changed}, relationships +${s.edges.added} -${s.edges.removed} ~${s.edges.changed}. Comment: ${r.action}${r.reason ? ` (${r.reason})` : ''}.`);
  } catch (e) {
    console.log(`::warning::Could not post the architecture diff: ${e.message}`);
  }
}
